es_gaming_home:
    resource: "@ESGamingHomeBundle/Resources/config/routing.yml"
    prefix:   /

es_gaming_new:
    resource: "@ESGamingNewBundle/Resources/config/routing.yml"
    prefix:   /new

es_gaming_user:
    resource: "@ESGamingUserBundle/Resources/config/routing.yml"
    prefix:   /user
