es_gaming_event:
    resource: "@ESGamingEventBundle/Resources/config/routing.yml"
    prefix:   /event

es_gaming_game:
    resource: "@ESGamingGameBundle/Resources/config/routing.yml"
    prefix:   /game

es_gaming_home:
    resource: "@ESGamingHomeBundle/Resources/config/routing.yml"
    prefix:   /

es_gaming_new:
    resource: "@ESGamingNewBundle/Resources/config/routing.yml"
    prefix:   /news

es_gaming_user:
    resource: "@ESGamingUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
es_gaming_comment:
    resource: "@ESGamingCommentBundle/Resources/config/routing.yml"
    prefix:   /comment

login:
    path: /login
    defaults: { _controller: ESGamingUserBundle:User:login }

login_check:
    pattern:   /login_check

logout:
    pattern: /logout