es_gaming_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ESGamingUserBundle:User:index }

user_register:
    path: /register
    defaults: { _controller: ESGamingUserBundle:User:register }

user_login:
    path: /login
    defaults: { _controller: ESGamingUserBundle:User:login }

user_logout:
    path: /logout
    defaults: { _controller: ESGamingUserBundle:User:logout }

es_gaming_user_get:
    path: /user/{id}
    defaults: { _controller: ESGamingUserBundle:User:user }
    requirements:
        id: \d+

es_gaming_user_all:
    path: /users
    defaults: { _controller: ESGamingUserBundle:User:userAll }


