es_gaming_user_register:
    path: /register
    defaults: { _controller: ESGamingUserBundle:User:register }

es_gaming_user_login:
    path: /login
    defaults: { _controller: ESGamingUserBundle:User:login }

es_gaming_user_get:
    path: /{id}
    defaults: { _controller: ESGamingUserBundle:User:user }
    requirements:
        id: \d+

es_gaming_user_all:
    path: /users
    defaults: { _controller: ESGamingUserBundle:User:userAll }

es_gaming_user_desactivate:
    path: /desactivate/{id}
    defaults: { _controller: ESGamingUserBundle:User:userDesactivate }

es_gaming_user_activate:
    path: /activate/{id}
    defaults: { _controller: ESGamingUserBundle:User:userActivate }

es_gaming_user_profile:
    path: /profile
    defaults: { _controller: ESGamingUserBundle:User:profile }

es_gaming_user_profile_id:
    path: /profile-{id}
    defaults: { _controller: ESGamingUserBundle:User:profile }

es_gaming_user_change_password:
    path: /profile/change-password
    defaults: { _controller: ESGamingUserBundle:User:changePassword }

es_gaming_user_edit_profile:
    path: /profile/edit
    defaults: { _controller: ESGamingUserBundle:User:editProfile }

es_gaming_user_editImage:
     path: /profile/edit-image
     defaults: { _controller: ESGamingUserBundle:User:editImage }